[package]
name = "streamline"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
sha2 = "0.10.8"
zip = "2.2.0"
indicatif = "0.17"
futures = "0.3.29"